-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 21:58:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Importes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Importes` (
  `idImportes` INT(8) NOT NULL,
  `idAlumno` INT(8) NOT NULL,
  `Tipo_Pago` VARCHAR(45) NOT NULL,
  `Importe` INT(4) NOT NULL,
  `DNI_Responsable` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idImportes`),
  INDEX `fk_Importes_Alumnos_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_Importes_Alumnos`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `mydb`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas` (
  `idNotas` INT(8) NOT NULL,
  `idAlumno` INT(8) NOT NULL,
  `LM` INT(2) NOT NULL,
  `CI` INT(2) NOT NULL,
  `CA` INT(2) NOT NULL,
  `Computo` INT(2) NOT NULL,
  `PS` INT(2) NOT NULL,
  `Religion` INT(2) NOT NULL,
  `EF` INT(2) NOT NULL,
  `Minichef` INT(2) NOT NULL,
  `Tutoria` INT(2) NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_Alumnos_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_Notas_Alumnos`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `mydb`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `idAlumno` INT(8) NOT NULL,
  `idImportes` INT(8) NOT NULL,
  `idNotas` INT(8) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Paterno` VARCHAR(45) NOT NULL,
  `Ape_Materno` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Edad` VARCHAR(45) NOT NULL,
  `Grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Alumnos_Importes1_idx` (`idImportes` ASC),
  INDEX `fk_Alumnos_Notas1_idx` (`idNotas` ASC),
  CONSTRAINT `fk_Alumnos_Importes1`
    FOREIGN KEY (`idImportes`)
    REFERENCES `mydb`.`Importes` (`idImportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_Notas1`
    FOREIGN KEY (`idNotas`)
    REFERENCES `mydb`.`Notas` (`idNotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docentes` (
  `idDocentes` INT(8) NOT NULL,
  `idEmpleados` INT(8) NOT NULL,
  `Salon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocentes`),
  INDEX `fk_Docentes_Empleados1_idx` (`idEmpleados` ASC),
  CONSTRAINT `fk_Docentes_Empleados1`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SalarioEmpleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SalarioEmpleados` (
  `idPagos` INT(8) NOT NULL,
  `idEmpleados` INT(8) NOT NULL,
  `SalarioNeto` VARCHAR(45) NOT NULL,
  `FechadePago` DATE NOT NULL,
  PRIMARY KEY (`idPagos`),
  INDEX `fk_SalarioEmpleados_Empleados1_idx` (`idEmpleados` ASC),
  CONSTRAINT `fk_SalarioEmpleados_Empleados1`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asistente_Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asistente_Matricula` (
  `idAsistente_Matricula` INT(8) NOT NULL,
  `idEmpleados` INT(8) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsistente_Matricula`),
  INDEX `fk_Asistente_Matricula_Empleados1_idx` (`idEmpleados` ASC),
  CONSTRAINT `fk_Asistente_Matricula_Empleados1`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT(8) NOT NULL,
  `idDocentes` INT(8) NOT NULL,
  `idAsistente_Matricula` INT(8) NOT NULL,
  `idPagos` INT(8) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Edad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleados`),
  INDEX `fk_Empleados_Docentes1_idx` (`idDocentes` ASC),
  INDEX `fk_Empleados_SalarioEmpleados1_idx` (`idPagos` ASC),
  INDEX `fk_Empleados_Asistente_Matricula1_idx` (`idAsistente_Matricula` ASC),
  CONSTRAINT `fk_Empleados_Docentes1`
    FOREIGN KEY (`idDocentes`)
    REFERENCES `mydb`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_SalarioEmpleados1`
    FOREIGN KEY (`idPagos`)
    REFERENCES `mydb`.`SalarioEmpleados` (`idPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_Asistente_Matricula1`
    FOREIGN KEY (`idAsistente_Matricula`)
    REFERENCES `mydb`.`Asistente_Matricula` (`idAsistente_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT(8) NOT NULL,
  `idEmpleados` INT(8) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Empleados1_idx` (`idEmpleados` ASC),
  CONSTRAINT `fk_Usuarios_Empleados1`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `idMatricula` INT(8) NOT NULL,
  `idUsuarios` INT(8) NOT NULL,
  `idAlumno` INT(8) NOT NULL,
  `idAsistente_Matricula` INT(8) NOT NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `fk_Matricula_Alumnos1_idx` (`idAlumno` ASC),
  INDEX `fk_Matricula_Usuarios1_idx` (`idUsuarios` ASC),
  INDEX `fk_Matricula_Asistente_Matricula1_idx` (`idAsistente_Matricula` ASC),
  CONSTRAINT `fk_Matricula_Alumnos1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `mydb`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Asistente_Matricula1`
    FOREIGN KEY (`idAsistente_Matricula`)
    REFERENCES `mydb`.`Asistente_Matricula` (`idAsistente_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
